when:
  - event: push
    branch: main

steps:
  - name: deploy
    image: codeberg.org/woodpecker-plugins/node-pm
    settings:
      run: deploy # script name
    environment:
      CLOUDFLARE_API_TOKEN:
        from_secret: cloudflare_api_token
