when:
  - event: push
    branch: main

workspace:
  base: /woodpecker
  path: src/mareshq-websites/vojtamares.cz

steps:
  - name: build
    image: codeberg.org/woodpecker-plugins/node-pm
    settings:
      run: build # script name
      with: pnpm # if `with` is set, enforce to use this package manager
      frozen_lockfile: true # recommended
      ignore_node_modules: true # recommended

  - name: deploy
    image: codeberg.org/woodpecker-plugins/node-pm
    settings:
      run: deploy # script name
      with: pnpm # if `with` is set, enforce to use this package manager
      environment:
        CLOUDFLARE_API_TOKEN:
          from_secret: cloudflare_api_token
